version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 408949636936.dkr.ecr.us-east-1.amazonaws.com
      - docker login --username AWS --password-stdin public.ecr.aws <<< $(aws ecr-public get-login-password --region us-east-1)
      - REPOSITORY_URI=408949636936.dkr.ecr.us-east-1.amazonaws.com/myapp-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Image tag is $IMAGE_TAG"
      - echo "Repository URI is $REPOSITORY_URI"
      - ls -la
  build:
    commands:
      - echo Building the Docker image...
      - docker build --no-cache -t $REPOSITORY_URI:$IMAGE_TAG . 2>&1
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"myapp-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
